INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (1, 'Jakarta Web Developers', 'https://picsum.photos/seed/community23/800/500', 'Komunitas developer web di Jakarta.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (2, 'Bandung Tech Community', 'https://picsum.photos/seed/community24/800/500', 'Komunitas teknologi dan software engineer Bandung.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (3, 'Go Indonesia', 'https://picsum.photos/seed/community25/800/500', 'Komunitas developer Go di Indonesia.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (4, 'React Indonesia', 'https://picsum.photos/seed/community26/800/500', 'Komunitas frontend developer yang menggunakan React.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (5, 'DevOps Nusantara', 'https://picsum.photos/seed/community27/800/500', 'Komunitas DevOps, cloud, dan infrastructure.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (6, 'UI UX Indonesia', 'https://picsum.photos/seed/community28/800/500', 'Komunitas desain produk digital.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (7, 'JavaScript Enthusiasts', 'https://picsum.photos/seed/community29/800/500', 'Tempat berbagi pengetahuan JavaScript.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (8, 'Python Indonesia', 'https://picsum.photos/seed/community30/800/500', 'Komunitas programmer Python Indonesia.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (9, 'Cloud Native Indonesia', 'https://picsum.photos/seed/community31/800/500', 'Komunitas teknologi cloud native.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (10, 'Data Science ID', 'https://picsum.photos/seed/community32/800/500', 'Komunitas data science dan analytics.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (11, 'AI Indonesia', 'https://picsum.photos/seed/community33/800/500', 'Komunitas AI dan machine learning.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (12, 'Cyber Security ID', 'https://picsum.photos/seed/community34/800/500', 'Komunitas keamanan siber.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (13, 'Docker Indonesia', 'https://picsum.photos/seed/community35/800/500', 'Komunitas pengguna Docker.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (14, 'Kubernetes Indonesia', 'https://picsum.photos/seed/community36/800/500', 'Komunitas Kubernetes dan container orchestration.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (15, 'Frontend ID', 'https://picsum.photos/seed/community37/800/500', 'Komunitas frontend developer Indonesia.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (16, 'Backend Developer ID', 'https://picsum.photos/seed/community38/800/500', 'Komunitas backend developer Indonesia.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (17, 'Database Indonesia', 'https://picsum.photos/seed/community39/800/500', 'Komunitas database engineer dan developer.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (18, 'Open Source Indonesia', 'https://picsum.photos/seed/community40/800/500', 'Komunitas kontributor open source.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (19, 'Tech Career Indonesia', 'https://picsum.photos/seed/community41/800/500', 'Komunitas karier dan pengembangan profesional teknologi.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (20, 'Software Architecture ID', 'https://picsum.photos/seed/community42/800/500', 'Komunitas software architecture.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (21, 'Mobile Developer ID', 'https://picsum.photos/seed/community43/800/500', 'Komunitas mobile developer.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (22, 'Product Tech Indonesia', 'https://picsum.photos/seed/community44/800/500', 'Komunitas product manager di industri teknologi.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (23, 'Testing Indonesia', 'https://picsum.photos/seed/community45/800/500', 'Komunitas software testing dan QA.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (24, 'TypeScript Indonesia', 'https://picsum.photos/seed/community46/800/500', 'Komunitas developer TypeScript.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (25, 'Node.js Indonesia', 'https://picsum.photos/seed/community47/800/500', 'Komunitas Node.js developer.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (26, 'Machine Learning ID', 'https://picsum.photos/seed/community48/800/500', 'Komunitas machine learning engineer.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (27, 'System Design Indonesia', 'https://picsum.photos/seed/community49/800/500', 'Komunitas belajar system design.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (28, 'API Developer Indonesia', 'https://picsum.photos/seed/community50/800/500', 'Komunitas API dan backend engineering.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (29, 'Tech Startup Indonesia', 'https://picsum.photos/seed/community51/800/500', 'Komunitas founder dan engineer startup teknologi.');
INSERT INTO public.communities OVERRIDING SYSTEM VALUE VALUES (30, 'Koda Tech Community', 'https://picsum.photos/seed/community52/800/500', 'Komunitas belajar dan berbagi pengalaman teknologi.');

SELECT pg_catalog.setval('public.communities_id_seq', 30, true);
