name: clone repo
on:
 push:
  tags: 
    - v*
jobs:
  checkout:
    runs-on: ubuntu-24.04
    steps:
      - name: greetings
        run: echo "${{github.repository_owner}}"
      - name: cloning my repo
        uses: actions/checkout@v6
      - run: |
          ls
          cat Makefile
        
        